### ISSUE TITLE
Adjust Phobos hardware trigger rate in the GUI

### ISSUE THREAD

**Issue by bcrutchleyi3dr** [i3drobotics/stereo-vision-toolkit#10]
It would be good to set the frames per second from the GUI as opposed to from re-uploading the arduino code.

**Comment by bknight-i3drobotics** [comment]
Arduino has been updated to support the setting of the FPS over serial. This system is implemented in ROS but not yet in the toolkit (coming soon). See ROS implementation [here](https://github.com/i3drobotics/i3dr_rosserial_phobos-ros.git)

**Comment by bknight-i3drobotics** [comment]
Can now control the hardware trigger from SVTK however, cannot use the same complicated serial communications message that rosserial requires so will need to re-upload arduino code when switching between ROS and SVTK
