### ISSUE TITLE
When building from source code and try to add CONFIG+=WITH_I3RDSGBM then while running abort() is called, why?

### ISSUE THREAD

**Issue by pythango-anuj** [i3drobotics/stereo-vision-toolkit#132]
When building from source code and try to add CONFIG+=WITH_I3RDSGBM then while running abort() is called, why?

**Comment by benknight135** [comment]
Could you confirm this is run with
```
CONFIG+=WITH_I3DRSGM
```
As there appears to be a typo in the WITH_I3RDSGBM in your question.

Also to confim, does everything work as expected when running without CONFIG+=WITH_I3DRSGM?

**Comment by pythango-anuj** [comment]
Sorry it's a typing mistake. It is built and run with CONFIG+=WITH_I3DRSGM.
Yes every run fine without this option.

**Comment by benknight135** [comment]
Okay, could you provide me with any details as to where the abort() is called?

Also I should mention that running with I3DRSGM enabled requires a valid license file that can be request from info@i3drobotics.com. Though the program should not crash if this is not available but wanted you to to be aware before you put the effort in to resolving this issue.

**Comment by pythango-anuj** [comment]
![WhatsApp Image 2022-08-30 at 10 10 37 AM](https://user-images.githubusercontent.com/53106657/187439235-2b45f0dc-af0f-411c-967d-df9b8a6932fa.jpeg)
After debugging i get this?

**Comment by benknight135** [comment]
I have been unable to replicate this issue on my local machine. Could you check there isn't any applications or dlls in the PATH variable that may be coflicting at runtime?

**Comment by pythango-anuj** [comment]
Ok no problem, actually please confirm me one thing. Is tmp.param and qtmp.param comes with license?

**Comment by pythango-anuj** [comment]
Also confirm that, We want to use real time scanning.. is it  possible to use real time reconstruction and registeration without using licensed I3DSGBM?
please confrim these two things.

**Comment by benknight135** [comment]
tmp.param is created at runtime and is used internally to monitor the parameters for the I3DRSGM matcher.
To answer your question about reconstruction and registration, you can use the alternative open source stereo matchers (BM, SGBM) if you do not have a license for I3DRSGM. However, SGBM is slow and BM tends to miss more features.
I3DR are experts at stereo 3D vision so if you have a specific use case in mind I would recommend giving us a message at info@i3drobotics.com

**Comment by pythango-anuj** [comment]
Ok Thank you so much for this conversation. It will help me a lot.
