### ISSUE TITLE
vcredist has a different name on some systems

### ISSUE THREAD

**Issue by bknight-i3drobotics** [i3drobotics/stereo-vision-toolkit#26]
Inno setup looks for vcredist, this has been found to have different names on some systems:
 - vcredist_x64.exe
 - vc_redist.x64.exe

Inno setup should be adjusted to account for these different files.

**Comment by benknight135** [comment]
VC_redist.x64.exe included in 3rdparty folder for consistent use and to make sure vc redist is for 2015-2019 rather than just 2019 as was included previously.
