### ISSUE TITLE
Add Titania support

### ISSUE THREAD

**Issue by bknight-i3drobotics** [i3drobotics/stereo-vision-toolkit#29]

**Comment by jveitchmichaelis** [comment]
https://github.com/i3drobotics/stereo-vision-toolkit/tree/vimba

Largely complete here, but needs user testing.

**Comment by jveitchmichaelis** [comment]
@bcrutchleyi3dr I think you've now tested this, so we can probably merge this to master?

**Comment by bknight-i3drobotics** [comment]
Vimba cameras used in Titania stereo system have been tested and work on the dev branch. Dev branch will be merged with master branch along with lots of other changes once tested and stable.
