### ISSUE TITLE
Stereo matcher doesn't work until single shot image has been taken (Deimos only)

### ISSUE THREAD

**Issue by bknight-i3drobotics** [i3drobotics/stereo-vision-toolkit#3]
After enabling the stereo matcher the disparity image doesn't appear unless single shot mode is toggled on and off. This only happens with the Deimos camera, Phobos works as expected.

Stereo matched enabled but not showing
![image](https://user-images.githubusercontent.com/44197387/47013749-242f6c80-d140-11e8-8150-8b10fd132fcd.png)
Single shot acquisition is clicked. Disparity window is working.
![image](https://user-images.githubusercontent.com/44197387/47013769-36110f80-d140-11e8-9633-02f86d27a21c.png)
Set back to free-running. Disparity window is working.
![image](https://user-images.githubusercontent.com/44197387/47013781-40cba480-d140-11e8-8afe-2f098bc48022.png)

**Comment by jveitchmichaelis** [comment]
Should be fixed: https://github.com/i3drobotics/stereo-vision-toolkit/commit/b974a80796bc0fe0c05c578918292485c48fdb8b
