### ISSUE TITLE
calibration didn't load

### ISSUE THREAD

**Issue by bcrutchleyi3dr** [i3drobotics/stereo-vision-toolkit#6]
Didn't load directly after loading calibration. Calibration loads fine if the program is re-started.

**Comment by jveitchmichaelis** [comment]
Hi Ben, do you mean you load a calibration folder and the images don't rectify automatically?

**Comment by bcrutchleyi3dr** [comment]
Hey,


Was a bit vague as I discussed with Ben 😊


The cal file didn't work when performing the following:

1) acquiring the cal images

2) running the cal wizard

3) loading the cal files.


If I then "x" out and start again it's fine. No biggie but probably something to look into when there's time.


Cheers

Ben

________________________________
