### ISSUE TITLE
Register if Phobos has been unplugged

### ISSUE THREAD

**Issue by bknight-i3drobotics** [i3drobotics/stereo-vision-toolkit#7]
If Phobos is unplugged while the program is running errors can occur. Currently unable to get the callback to trigger when the device is unplugged. Ideally the tab windows should be disabled if the unplugged event it triggered.
(This process is currently working for Deimos however this uses a much simpler process)

**Comment by jveitchmichaelis** [comment]
Possibly requires a flag:

https://github.com/i3drobotics/stereo-vision-toolkit/blob/03d5cdb652aefc631062d0a49437ecfa529e153d/src/cameraimagingsource.cpp#L83

Should be:

`handle.addListener((DShowLib::GrabberListener*)listener, eALL);`

per https://www.theimagingsource.com/support/documentation/ic-imaging-control-cpp/meth_descGrabber_addListener.htm.

**Comment by bknight-i3drobotics** [comment]
To keep things simple a system has been added to the abstract stereo camera class that will disconnect the camera if it looses more than n frames consecutively. Each child class has a 'disconnectCamera' method that is able to close the camera connections safely even if a device is manually removed. 
This has been tested with Basler USB, TIS, and Deimos. 
There an issue with the TIS cameras that the TIS software cannot tell if a camera has been left in an unsafe state when they are reconnected so this will cause an occasional crash. However, if the user restarts the software it closes the connection properly and fixes the issue. As this issue is no longer relevant this issue, this issue will be closed. (New issue: #46 )
