### ISSUE TITLE
Load video not longer works

### ISSUE THREAD

**Issue by bknight-i3drobotics** [i3drobotics/stereo-vision-toolkit#8]
When a video is loaded only the first frame is loaded and the video won't play

**Comment by jveitchmichaelis** [comment]
Partial fix https://github.com/i3drobotics/stereo-vision-toolkit/commit/a6175f9abd10c249743f175baf9e55f4b5f84f2f

Should at least play now.

**Comment by jveitchmichaelis** [comment]
Can I close this?
