### ISSUE TITLE
disable rectify image when loading in videos

### ISSUE THREAD

**Issue by bcrutchleyi3dr** [i3drobotics/stereo-vision-toolkit#9]
Videos save the rectified images. The rectified box is checked as default and hence buggers up the matching when a video is loaded.

**Comment by jveitchmichaelis** [comment]
So you load the video (calibrated), another calibration is already loaded and you can't disable rectification?

**Comment by bcrutchleyi3dr** [comment]
Sorry Josh, that makes me sound like a princess that can't click a button :) 

I discussed this with Ben stating that a user might think it's not working when it's actually just because it has rectified twice. It was mainly mean't as a good to have when we release it properly.

I'll include the assignees as Ben in the future to avoid confusion :)

**Comment by jveitchmichaelis** [comment]
No worries. :)

One option would be to have a dialog menu when loading to choose e.g.frame
rate (currently we guess), calibration/pre-calibrated, etc.

**Comment by bknight-i3drobotics** [comment]
See enhancement: #25
